import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/lib/utils/provider";
import ReduxProvider from "./ReduxProvider";
import MuiTheme from "./MuiTheme";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  
  return (
    <html lang="en">
      <Providers>
        <MuiTheme>
          <body className={inter.className}>{children}</body>
        </MuiTheme>
        <ReduxProvider />
        <ToastContainer />
      </Providers>
    </html>
  );
}
